//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_filtre_sistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaDBEntities : DbContext
    {
        public CinemaDBEntities()
            : base("name=CinemaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinemas> Cinemas { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Genres_Movies> Genres_Movies { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Showings> Showings { get; set; }
    }
}
