//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_filtre_sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showings
    {
        public int ShowingID { get; set; }
        public System.DateTime ShowTime { get; set; }
        public decimal TicketPrice { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> HallID { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
