//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int UserID { get; set; }
        public int ShowingID { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public Nullable<int> SeatID { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Showings Showings { get; set; }
        public virtual Users Users { get; set; }
    }
}
