//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<System.DateTime> PaymentTimestamp { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
