//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int MovieID { get; set; }
        public Nullable<int> ShowingID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public int SeatCount { get; set; }
        public decimal BaseTotal { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FinalTotal { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual Showings Showings { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
