//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int TicketID { get; set; }
        public string SeatNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShowingID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Reservations Reservations { get; set; }
        public virtual Seats Seats { get; set; }
        public virtual Showings Showings { get; set; }
        public virtual Users Users { get; set; }
    }
}
