//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top10Movies
    {
        public int TopMovieID { get; set; }
        public int MovieID { get; set; }
        public int RankOrder { get; set; }
        public System.DateTime WeekOf { get; set; }
    
        public virtual Movies Movies { get; set; }
    }
}
