//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Campaigns
    {
        public int UserCampaignID { get; set; }
        public int UserID { get; set; }
        public int CampaignID { get; set; }
        public System.DateTime RedeemedDate { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual Users Users { get; set; }
    }
}
